# Generated by Django 5.2.1 on 2025-05-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='date',
        ),
    ]
